### ISSUE TITLE
IsReadable function bug

### ISSUE THREAD

**Issue by WBGlIl** [illegal-instruction-co/ii-importer#1]
```cpp
static StringToolkit IsReadable(char* str) {
	if (str == nullptr)
		SetAs<bool>(false);

	MEMORY_BASIC_INFORMATION mbi;

	VirtualQuery(str, &mbi, sizeof(mbi));

	SetAs<bool>(mbi.Protect & PAGE_READONLY || mbi.Protect & PAGE_READWRITE);

	return StringToolkit();
}
```
![image](https://user-images.githubusercontent.com/29301859/224623504-ad9649f9-d842-40e1-876c-d2aac9a0f81f.png)
The memory attribute here is likely to be PAGE_EXECUTE_READ

**Comment by illegal-instruction-co** [comment]
You have literally discovered a logical inconsistency on IsReadable fn. This function only designed for checking if the data stored in export table is readable or not.  A data stored in the Export table must really be both executable and readable.

I am suggesting to solve this issue by arrange code as: 

```cpp
static StringToolkit IsReadable(const char* str) {
	if (str == nullptr)
		SetAs<bool>(false);

	MEMORY_BASIC_INFORMATION mbi;

	VirtualQuery(str, &mbi, sizeof(mbi));

	SetAs<bool>(mbi.Protect & PAGE_EXECUTE_READ || mbi.Protect & PAGE_READONLY || mbi.Protect & PAGE_READWRITE);

	return StringToolkit();
}
```

after your approve, ill commit the required changes into main branch as 1.0.4 tag.

**Comment by WBGlIl** [comment]
> You have literally discovered a logical inconsistency on IsReadable fn. This function only designed for checking if the data stored in export table is readable or not. A data stored in the Export table must really be both executable and readable.
> 
> I am suggesting to solve this issue by arrange code as:
> 
> ```c++
> static StringToolkit IsReadable(const char* str) {
> 	if (str == nullptr)
> 		SetAs<bool>(false);
> 
> 	MEMORY_BASIC_INFORMATION mbi;
> 
> 	VirtualQuery(str, &mbi, sizeof(mbi));
> 
> 	SetAs<bool>(mbi.Protect & PAGE_EXECUTE_READ || mbi.Protect & PAGE_READONLY || mbi.Protect & PAGE_READWRITE);
> 
> 	return StringToolkit();
> }
> ```
> 
> after your approve, ill commit the required changes into main branch as 1.0.4 tag.

Actually we don't need IsReadable function, we just need to change AddressOfFunctions to NumberOfNames

```cpp
std::unordered_map<std::string_view, uint64_t> Fetch() {

	std::unordered_map<std::string_view, uint64_t> res;
	PDWORD addr, name;
	PWORD ordinal;

	addr = reinterpret_cast<PDWORD>(reinterpret_cast<LPBYTE>(m_module) + m_exportDirectory->AddressOfFunctions);
	name = reinterpret_cast<PDWORD>(reinterpret_cast<LPBYTE>(m_module) + m_exportDirectory->AddressOfNames);
	ordinal = reinterpret_cast<PWORD>(reinterpret_cast<LPBYTE>(m_module) + m_exportDirectory->AddressOfNameOrdinals);

	for (int i = 0; i < m_exportDirectory->NumberOfNames; i++) {
		res.insert({ std::move(std::string_view(static_cast<char*>(m_module) + name[i])), (uint64_t)m_module + addr[ordinal[i]] });
	}
	return res;
}
```

**Comment by illegal-instruction-co** [comment]
A really useful discovery. Ngl, I didn't even know NumberOfNames was there. Thank you for refactoring, in this way our code was shortened by 60 lines and unnecessary WinAPI functions were not called.
